### ISSUE TITLE
Enhance radioList and checkboxList styles

### ISSUE THREAD

**Issue by kartik-v** [kartik-v/yii2-widget-activeform#129]

**Comment by poda5d2** [comment]
In this version the checkboxList creates the fields with different class names than before.
Instead of form-check and form-check-label, fields are now created with the class names bs-checkbox and bs-checkbox-label.
Because of this, the fields do not appear in the correct style.

What is the reason for changing class names with the same settings?
bsVersion: 4.x
Custom control: not

Regards: David
